"""fix db_2

Revision ID: b71a8fe3b4c5
Revises: 266e33ea1192
Create Date: 2026-01-06 17:22:16.700610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71a8fe3b4c5'
down_revision: Union[str, Sequence[str], None] = '266e33ea1192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_elements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('access_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_element_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('read_permission', sa.Boolean(), nullable=False),
    sa.Column('read_all_permissions', sa.Boolean(), nullable=False),
    sa.Column('create_permission', sa.Boolean(), nullable=False),
    sa.Column('update_permission', sa.Boolean(), nullable=False),
    sa.Column('update_all_permissions', sa.Boolean(), nullable=False),
    sa.Column('delete_permission', sa.Boolean(), nullable=False),
    sa.Column('delete_all_permissions', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_element_id'], ['business_elements.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=35), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('access_rules')
    op.drop_table('roles')
    op.drop_table('business_elements')
    # ### end Alembic commands ###
